name: Continuous Integration
on:
  pull_request:
    paths:
      - 'frontend/**'
defaults:
  run:
    working-directory: frontend

jobs:
  npm-install: # with node_modules caching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci --ignore-scripts

  unit-tests:
    needs: [npm-install]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Run eslin report
        run: npm run lint:report

      - name: Upload eslint report for code-quality
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-report
          path: reports/
          retention-days: 1

  code-quality:
    needs: [npm-install]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage report for unit-tests
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: |
            reports/
            coverage/
          retention-days: 1

  sonar-analysis:
    needs: [unit-tests, code-quality]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
