name: Continuous Integration
on:
  pull_request:
    types:
      - opened
    paths:
      - 'frontend/**'
defaults:
  run:
    working-directory: frontend

jobs:
  npm-install: # with node_modules caching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

  unit-tests:
    needs: [npm-install]

    steps:
      - uses: actions/cache@v3

      - name: Run eslin report
        run: npm run lint:report

      - name: Upload eslint report for code-quality
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-report
          path: reports/
          retention-days: 1

  code-quality:
    needs: [npm-install]

    steps:
      - uses: actions/cache@v3

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage report for unit-tests
        uses: actions/upload-artifact@v3
        with:
          - name: test-coverage-report
            path: |
              reports/
              coverage/
            retention-days: 1

  sonar-analysis:
    needs: [unit-tests, code-quality]
    runs-on: ubuntu-latest
    container: sonarsource/sonar-scanner-cli:latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
      - run: sonar-scanner -Dsonar.qualitygate.wait=true
